version: '3'
services:
  # NGINX
  nginx:
    image: nginx:stable-alpine3.17-slim
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - node
  # NODE
  node:
    build:
      context: .
      args:
        - NODE_ENV=production
    environment:
      - PORT=3000
      - NODE_ENV=production
    command: node index.js
    depends_on:
      - mongo
  # MONGO
  mongo:
    container_name: mongodb
    image: mongo:4.2.24-bionic
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
