version: '3'
services:
  # NGINX
  nginx:
    image: nginx:stable-alpine3.17-slim
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
    ports:
      - "3000:80"
  # NODE
  node:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - "./:/app"
      - "/app/node_modules"
    environment:
      - PORT=3000
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - mongo
  # MONGO
  mongo:
    image: mongo:4.2.24-bionic
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "3001:27017"
    volumes:
      - mongo-db:/data/db
  # MONGO DATABASE EDITOR
  dbeditor:
    image: mongo-express:0.54.0
    ports:
      - "3002:8081"
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
    depends_on:
      - mongo
volumes:
  mongo-db:
