version: '3'
services:
  # NGINX
  nginx:
    ports:
      - "3000:80"
  # NODE
  node:
    build:
      args:
        - NODE_ENV=development
    volumes:
      - "./:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=development
    command: npm run dev
  # MONGO
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "3001:27017"
  # MONGO DATABASE EDITOR
  dbeditor:
    image: mongo-express:1.0.0-alpha.4
    ports:
      - "3002:8081"
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
    depends_on:
      - mongo
